export const NEW_ORDER = "NEW_ORDER";
export const ADD_ITEM_TO_ORDER = "ADD_ITEM_TO_ORDER";
export const REMOVE_ITEM_FROM_ORDER = "REMOVE_ITEM_FROM_ORDER";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
