//cashier auth actions
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

//event actions
export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const RECEIVE_EVENTS = "RECEIVE_EVENTS";
export const SET_EVENT = "SET_EVENT";
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED";

//customer actions
export const REQUEST_CUSTOMERS = "REQUEST_CUSTOMERS";
export const RECEIVE_CUSTOMERS = "RECEIVE_CUSTOMERS";
//export const SET_CUSTOMER = "SET_CUSTOMER";
export const FETCH_CUSTOMERS_FAILED = "FETCH_CUSTOMERS_FAILED";

//product actions
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

//order actions
export const SET_PRODUCT_QUANTITY = "SET_PRODUCT_QUANTITY";
export const RESET_ORDER = "RESET_ORDER";
export const SET_ORDER_CUSTOMER = "SET_ORDER_CUSTOMER";
export const SET_MINIMUM_ORDER_TOPUP_AMOUNT = "SET_MINIMUM_ORDER_TOPUP_AMOUNT";
export const SET_ORDER_TOPUP_AMOUNT = "SET_ORDER_TOPUP_AMOUNT";
export const LOCAL_ORDER = "LOCAL_ORDER";
export const ORDER_SYNC_STARTED = "ORDER_SYNC_STARTED";
export const ORDER_SYNC_COMPLETE = "ORDER_SYNC_COMPLETE";
export const ORDER_SYNC_FAILED = "ORDER_SYNC_FAILED";


//topup actions
export const LOCAL_TOPUP = "LOCAL_TOPUP";
export const TOPUP_SYNC_STARTED = "TOPUP_SYNC_STARTED";
export const TOPUP_SYNC_COMPLETE = "TOPUP_SYNC_COMPLETE";
export const TOPUP_SYNC_FAILED = "TOPUP_SYNC_FAILED";
export const SET_TOPUP_AMOUNT = "SET_TOPUP_AMOUNT";
export const SET_TOPUP_CUSTOMER = "SET_TOPUP_CUSTOMER";

//message actions
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_ERROR = "SEND_ERROR";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const REMOVE_ERROR = "REMOVE_ERROR";

//subscription actions
export const REQUEST_SUBSCRIPTIONS = "REQUEST_SUBSCRIPTIONS";
export const RECEIVE_SUBSCRIPTIONS = "RECEIVE_SUBSCRIPTIONS";
export const FETCH_SUBSCRIPTIONS_FAILED = "FETCH_SUBSCRIPTIONS_FAILED";

//rollback actions
export const ROLLBACK_SYNC_STARTED = "ROLLBACK_SYNC_STARTED";
export const ROLLBACK_SYNC_COMPLETE = "ROLLBACK_SYNC_COMPLETE";
export const ROLLBACK_SYNC_FAILED = "ROLLBACK_SYNC_FAILED";
export const LOCAL_ROLLBACK ="LOCAL_ROLLBACK";

//settings actions
export const SET_HISTORY_COUNT = "SET_HISTORY_COUNT";




